# Generated by Django 4.2.5 on 2023-10-04 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='CommonIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bulb')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
