# Generated by Django 4.2.5 on 2023-10-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bulb_commonissue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
