# Generated by Django 4.2.5 on 2023-10-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSignalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bulb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentLeakeageIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bulb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokenWireIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bulb')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
