# Generated by Django 4.2.5 on 2023-10-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_nosignalissue_currentleakeageissue_brokenwireissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulb',
            old_name='Location',
            new_name='location',
        ),
    ]
